"""Add severity indexes

Revision ID: cc0cc8a0bef0
Revises: 
Create Date: 2026-04-23 03:28:39.164199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc0cc8a0bef0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_id'), 'api_keys', ['id'], unique=False)
    op.create_index(op.f('ix_api_keys_key'), 'api_keys', ['key'], unique=True)
    op.create_table('devices',
    sa.Column('mac', sa.String(), nullable=False),
    sa.Column('hostname', sa.String(), nullable=True),
    sa.Column('hostname_source', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('ip_history', sa.JSON(), nullable=True),
    sa.Column('vendor', sa.String(), nullable=True),
    sa.Column('is_randomized_mac', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('mac')
    )
    op.create_index(op.f('ix_devices_hostname'), 'devices', ['hostname'], unique=False)
    op.create_index(op.f('ix_devices_mac'), 'devices', ['mac'], unique=False)
    op.create_table('processed_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processed_messages_id'), 'processed_messages', ['id'], unique=False)
    op.create_index(op.f('ix_processed_messages_timestamp'), 'processed_messages', ['timestamp'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('alert_key', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('occurrence_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('device_mac', sa.String(), nullable=True),
    sa.Column('dest_ip', sa.String(), nullable=True),
    sa.Column('dest_domain', sa.String(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.Column('action_taken', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['device_mac'], ['devices.mac'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_alert_key'), 'alerts', ['alert_key'], unique=True)
    op.create_index(op.f('ix_alerts_device_mac'), 'alerts', ['device_mac'], unique=False)
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_alerts_timestamp'), 'alerts', ['timestamp'], unique=False)
    op.create_table('anomalies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('device_mac', sa.String(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('recommendation', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['device_mac'], ['devices.mac'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomalies_device_mac'), 'anomalies', ['device_mac'], unique=False)
    op.create_index(op.f('ix_anomalies_id'), 'anomalies', ['id'], unique=False)
    op.create_index(op.f('ix_anomalies_severity'), 'anomalies', ['severity'], unique=False)
    op.create_index(op.f('ix_anomalies_timestamp'), 'anomalies', ['timestamp'], unique=False)
    op.create_table('device_baselines',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('device_mac', sa.String(), nullable=True),
    sa.Column('time_window', sa.String(), nullable=True),
    sa.Column('avg_bytes_per_hour', sa.Integer(), nullable=True),
    sa.Column('top_ports', sa.JSON(), nullable=True),
    sa.Column('top_domains', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['device_mac'], ['devices.mac'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_baselines_device_mac'), 'device_baselines', ['device_mac'], unique=False)
    op.create_index(op.f('ix_device_baselines_id'), 'device_baselines', ['id'], unique=False)
    op.create_table('traffic_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('timestamp_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timestamp_end', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('src_ip', sa.String(), nullable=True),
    sa.Column('dest_ip', sa.String(), nullable=True),
    sa.Column('src_mac', sa.String(), nullable=True),
    sa.Column('dest_mac', sa.String(), nullable=True),
    sa.Column('device_mac', sa.String(), nullable=True),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('protocol', sa.String(), nullable=True),
    sa.Column('src_port', sa.Integer(), nullable=True),
    sa.Column('dest_port', sa.Integer(), nullable=True),
    sa.Column('bytes', sa.Integer(), nullable=True),
    sa.Column('packets', sa.Integer(), nullable=True),
    sa.Column('tcp_flags_seen', sa.Integer(), nullable=True),
    sa.Column('min_ttl', sa.Integer(), nullable=True),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('domain_source', sa.String(), nullable=True),
    sa.Column('dest_country', sa.String(), nullable=True),
    sa.Column('is_suspicious', sa.Boolean(), nullable=True),
    sa.Column('risk_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['device_mac'], ['devices.mac'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traffic_records_dest_ip'), 'traffic_records', ['dest_ip'], unique=False)
    op.create_index(op.f('ix_traffic_records_device_mac'), 'traffic_records', ['device_mac'], unique=False)
    op.create_index(op.f('ix_traffic_records_id'), 'traffic_records', ['id'], unique=False)
    op.create_index(op.f('ix_traffic_records_src_ip'), 'traffic_records', ['src_ip'], unique=False)
    op.create_index(op.f('ix_traffic_records_timestamp_end'), 'traffic_records', ['timestamp_end'], unique=False)
    op.create_index(op.f('ix_traffic_records_timestamp_start'), 'traffic_records', ['timestamp_start'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_traffic_records_timestamp_start'), table_name='traffic_records')
    op.drop_index(op.f('ix_traffic_records_timestamp_end'), table_name='traffic_records')
    op.drop_index(op.f('ix_traffic_records_src_ip'), table_name='traffic_records')
    op.drop_index(op.f('ix_traffic_records_id'), table_name='traffic_records')
    op.drop_index(op.f('ix_traffic_records_device_mac'), table_name='traffic_records')
    op.drop_index(op.f('ix_traffic_records_dest_ip'), table_name='traffic_records')
    op.drop_table('traffic_records')
    op.drop_index(op.f('ix_device_baselines_id'), table_name='device_baselines')
    op.drop_index(op.f('ix_device_baselines_device_mac'), table_name='device_baselines')
    op.drop_table('device_baselines')
    op.drop_index(op.f('ix_anomalies_timestamp'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_severity'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_id'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_device_mac'), table_name='anomalies')
    op.drop_table('anomalies')
    op.drop_index(op.f('ix_alerts_timestamp'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_device_mac'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_alert_key'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_processed_messages_timestamp'), table_name='processed_messages')
    op.drop_index(op.f('ix_processed_messages_id'), table_name='processed_messages')
    op.drop_table('processed_messages')
    op.drop_index(op.f('ix_devices_mac'), table_name='devices')
    op.drop_index(op.f('ix_devices_hostname'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_api_keys_key'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_id'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
